modLoader = "javafml"
loaderVersion = "[41,)"

displayURL = "https://github.com/itzme1on/AlcoCraft-Plus"
issueTrackerURL = "https://github.com/itzme1on/AlcoCraft-Plus/issues"

license = "All Rights Reserved"

[[mods]]
modId = "alcocraftplus"
version = "${version}"
displayName = "AlcoCraft+"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''
With this mod you will be able to brew beer and treat your good friends with it!
'''
logoFile = "logo.png"

[[dependencies.alcocraftplus]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alcocraftplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.19.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.alcocraftplus]]
modId = "architectury"
mandatory = true
versionRange = "[5.14.84,)"
ordering = "AFTER"
side = "BOTH"
