plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id "com.hypherionmc.modutils.modpublisher" version "2.1.8"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common

    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    modImplementation "dev.architectury:architectury-fabric:${architectury_api_version}"

    modImplementation "com.terraformersmc:modmenu:${modmenu_version}"

    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    modCompileOnlyApi "mezz.jei:jei-${minecraft_version}-fabric-api:${jei_version}"
    modCompileOnlyApi "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
    modCompileOnlyApi "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:${rei_version}"

    modRuntimeOnly "mezz.jei:jei-${minecraft_version}-fabric:${jei_version}"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"

    common(project(path: ':Common', configuration: 'namedElements')) { transitive false }
    shadowBundle project(path: ':Common', configuration: 'transformProductionFabric')
}

processResources {
    filesMatching('fabric.mod.json') {
        expand(
                "mod_authors": project.findProperty("mod_authors"),
                "mod_discord_url": project.findProperty("mod_discord_url"),
                "mod_description": project.findProperty("mod_description"),
                "mod_display_name": project.findProperty("mod_display_name"),
                "mod_git_url": project.findProperty("mod_git_url"),
                "mod_id": project.findProperty("mod_id"),
                "mod_issues_url": project.findProperty("mod_issues_url"),
                "mod_license": project.findProperty("mod_license"),
                "mod_name": project.findProperty("mod_display_name"),
                "mod_page_url": project.findProperty("mod_page_url"),
                "mod_version": project.findProperty("mod_version"),
                "fabric_loader_version": project.findProperty("fabric_loader_version"),
                "minecraft_min_version": project.findProperty("minecraft_min_version"),
                "minecraft_max_version": project.findProperty("minecraft_max_version"),
                "java_version": project.findProperty("java_version"),
                "architectury_api_version": project.findProperty("architectury_api_version"),
        )
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
    archiveClassifier = 'fabric'
}

publisher {
    def mcVersionsFabric = (rootProject.ext.minecraftGameVersions as List).collect { it.toString() } as String[]
    def changelogFile = rootProject.file("CHANGELOG.md")
    def changelogText = changelogFile.exists() ? changelogFile.getText("UTF-8") : ""

    apiKeys {
        modrinth System.getenv("MODRINTH_TOKEN")
        curseforge System.getenv("CURSEFORGE_TOKEN")
    }

    setCurseID((rootProject.findProperty("mod_curseforge_id") ?: "").toString())

    setModrinthID((rootProject.findProperty("mod_modrinth_id") ?: "").toString())

    setVersionType((rootProject.findProperty("release_channel") ?: "release").toString())

    setChangelog(changelogText)

    setProjectVersion(rootProject.mod_version)

    setDisplayName("${rootProject.mod_display_name} ${rootProject.mod_version} (${project.name} ${rootProject.minecraft_version})")

    setGameVersions(*mcVersionsFabric)

    setLoaders("fabric")

    setCurseEnvironment("both")

    setArtifact(tasks.remapJar)

    modrinthDepends {
        required("architectury-api", "fabric-api")
        optional("jei", "rei")
    }

    curseDepends {
        required("architectury-api", "fabric-api")
        optional("jei", "roughly-enough-items")
    }
}
