# Project
maven_group=me.itzme1on
release_channel=release

# Common
minecraft_version=1.20.1
enabled_platforms=fabric,forge,neoforge

# Forge
forge_version=47.3.12
forge_version_range=[47,)
forge_loader_version_range=[47,)

# Fabric
fabric_api_version=0.92.2+1.20.1
fabric_loader_version=0.16.9

# Mod options
mod_version=2.0.2
mod_id=alcocraftplus
mod_display_name=AlcoCraft+
mod_authors=itzme1on
mod_description=With this mod you will be able to brew beer and treat your good friends with it!
mod_license=All Rights Reserved
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/alcocraft
mod_issues_url=https://github.com/itzme1on/AlcoCraft-Plus/issues
mod_git_url=https://github.com/itzme1on/AlcoCraft-Plus
mod_scm_url=scm:git:git@github.com:itzme1on/AlcoCraft-Plus.git
mod_discord_url=https://discord.gg/Qsr8cAdjxW
mod_curseforge_id=847059
mod_modrinth_id=6t2MdNbo

# Dependencies
architectury_api_version=9.2.14
modmenu_version=7.2.2
parchment_version=2023.09.03
jei_version=15.2.0.27
modrinth_project_id=6t2MdNbo

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true