# Project
maven_group                     = me.itzme1on
release_channel                 = release

java_version                    = 25

# Common
minecraft_version               = 26.1.2
minecraft_min_version           = 26.1.2
minecraft_max_version           = 26.1.3
enabled_platforms               = fabric,neoforge

# Fabric
fabric_loader_version           = 0.18.4
fabric_api_version              = 0.151.0+26.1.2

# Neoforge
neoforge_version                = 26.1.2.76
neoforge_version_range          = [26,)
neoforge_loader_version_range   = [2,)

# Mod options
mod_version                     = 2.1.3
mod_id                          = alcocraftplus
mod_display_name                = AlcoCraft+
mod_authors                     = itzme1on
mod_contributors                = maeko802
mod_description                 = With this mod you will be able to brew beer and treat your good friends with it!
mod_license                     = All Rights Reserved
mod_page_url                    = https://www.curseforge.com/minecraft/mc-mods/alcocraft
mod_issues_url                  = https://github.com/itzme1on/AlcoCraft-Plus/issues
mod_git_url                     = https://github.com/itzme1on/AlcoCraft-Plus
mod_scm_url                     = scm:git:git@github.com:itzme1on/AlcoCraft-Plus.git
mod_discord_url                 = https://discord.gg/Qsr8cAdjxW
mod_curseforge_id               = 847059
mod_modrinth_id                 = 6t2MdNbo

# Dependencies
architectury_api_version        = 20.0.4
jei_version                     = 29.6.2.31
modmenu_version                 = 18.0.0-beta.1

# Done to increase the memory available to Gradle.
org.gradle.jvmargs              = -Xmx4G
org.gradle.parallel             = true
