# Project
maven_group=me.itzme1on
release_channel=release

# Common
minecraft_version=1.20.2
enabled_platforms=fabric,forge,neoforge

# Forge
forge_version=48.1.0
forge_version_range=[48,)
forge_loader_version_range=[48,)

# Fabric
fabric_api_version=0.91.2+1.20.2
fabric_loader_version=0.16.9

# Mod options
mod_version=2.0.2
mod_id=alcocraftplus
mod_display_name=AlcoCraft+
mod_authors=itzme1on
mod_contributors=Dalethium
mod_description=With this mod you will be able to brew beer and treat your good friends with it!
mod_license=All Rights Reserved
mod_page_url=https://www.curseforge.com/minecraft/mc-mods/alcocraft
mod_issues_url=https://github.com/itzme1on/AlcoCraft-Plus/issues
mod_git_url=https://github.com/itzme1on/AlcoCraft-Plus
mod_scm_url=scm:git:git@github.com:itzme1on/AlcoCraft-Plus.git
mod_discord_url=https://discord.gg/Qsr8cAdjxW
mod_curseforge_id=847059
mod_modrinth_id=6t2MdNbo

# Dependencies
architectury_api_version=10.1.20
modmenu_version=8.0.1
parchment_version=2023.12.10
jei_version=16.0.0.2

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true