include('common', 'fabric', 'forge')

pluginManagement.repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url "https://maven.fabricmc.net/" }
    maven { url "https://maven.architectury.dev/" }
    maven { url "https://files.minecraftforge.net/maven/" }
    maven { url "https://maven.firstdark.dev/releases" }
}

rootProject.name = 'AlcoCraft+'

project(":common").name = "Common"
project(":forge").name = "Forge"
project(":fabric").name = "Fabric"