blank_issues_enabled: false
contact_links:
  - name: Questions / Support (Q&A)
    url: https://discord.gg/Qsr8cAdjxW
    about: Join our Discord community for gameplay questions, recipes or mod help.