plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
    id 'com.modrinth.minotaur'
}

version = rootProject.mod_version

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
        convertAccessWideners.set(true)
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

repositories {
    maven { url 'https://maven.shedaniel.me/' }
    maven { url 'https://maven.minecraftforge.net/' }
}

dependencies {
    forge "net.minecraftforge:forge:$rootProject.minecraft_version-$rootProject.forge_version"

    modApi "dev.architectury:architectury-forge:$rootProject.architectury_api_version"

    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    modRuntimeOnly("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    common(project(path: ":common", configuration: "namedElements")) {
        transitive = false
        exclude(group: "net.fabricmc.fabric-api")
    }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}

processResources {
    filesMatching("META-INF/mods.toml") {
        expand(
                "architectury_api_version": project.findProperty("architectury_api_version"),
                "forge_loader_version_range": project.findProperty("forge_loader_version_range"),
                "forge_version_range": project.findProperty("forge_version_range"),
                "mod_authors": project.findProperty("mod_authors"),
                "mod_discord_url": project.findProperty("mod_discord_url"),
                "mod_description": project.findProperty("mod_description"),
                "mod_display_name": project.findProperty("mod_display_name"),
                "mod_git_url": project.findProperty("mod_git_url"),
                "mod_id": project.findProperty("mod_id"),
                "mod_issues_url": project.findProperty("mod_issues_url"),
                "mod_license": project.findProperty("mod_license"),
                "mod_name": project.findProperty("mod_display_name"),
                "mod_page_url": project.findProperty("mod_page_url"),
                "mod_version": project.findProperty("mod_version")
        )
    }
}


shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier.set("dev-shadow")
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = mod_modrinth_id
    versionNumber = mod_version
    versionType = release_channel
    loaders = ["forge"]
    file = tasks.named("jar").get().archiveFile

    if (changelog_file.exists()) {
        changelog = changelog_file.text
    }

    dependencies {
        required.project 'architectury-api'
        optional.project 'jei'
    }
}