plugins {
    id 'architectury-plugin'
    id 'java'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    compileOnly "me.shedaniel:RoughlyEnoughItems-api:${rootProject.rei_version}"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}