plugins {
    id 'java-library'
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
    it.options.encoding = "UTF-8"
}

repositories {
    mavenCentral()
    maven { url = "https://maven.shedaniel.me/" }
}

dependencies {
    compileOnlyApi "me.shedaniel:RoughlyEnoughItems-api:${rootProject.rei_version}"
    api "org.apache.logging.log4j:log4j-api:2.20.0"
    implementation "org.apache.logging.log4j:log4j-core:2.20.0"
}