plugins {
    id "dev.architectury.loom"
    id "com.github.johnrengelman.shadow" version '8.1.1'
    id 'com.modrinth.minotaur'
}

def changelog_file = rootProject.file('CHANGELOG.md')
//def parchmentCoords = "org.parchmentmc.data:parchment-${rootProject.minecraft_version}:${rootProject.parchment_version}@zip"

loom {
    accessWidenerPath = file("../common/src/main/resources/alcocraftplus.accesswidener")
}

repositories {
    mavenCentral() // For general dependencies
    maven { url = "https://maven.architectury.dev/" } // For Architectury dependencies
    maven { url = "https://maven.fabricmc.net/" } // For Fabric dependencies
    maven { url = "https://maven.neoforged.net/releases/" } // NeoForge Maven repository
    maven { url = "https://maven.shedaniel.me/" } // For RoughlyEnoughItems (REI) or similar mods
    maven { url = "https://libraries.minecraft.net/" } // Minecraft libraries
    maven { url = "https://maven.parchmentmc.org" } // Required for Parchment mappings
}

configurations {
    common
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${rootProject.minecraft_version}:${rootProject.parchment_version}@zip")
    }
    modImplementation "net.neoforged:neoforge:${rootProject.neoforge_version}"
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    modApi "dev.architectury:architectury-neoforge:$rootProject.architectury_api_version"
    modRuntimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rootProject.rei_version}"
    common(project(path: ":common", configuration: "namedElements")) {
        transitive = false
    }
    shadowBundle(project(path: ":common", configuration: "transformProductionNeoForge")) {
        transitive = false
    }
}

processResources {
    inputs.property 'neoforge_version', rootProject.neoforge_version

    filesMatching("META-INF/neoforge.mods.toml") {
        expand(
                "mod_id": rootProject.mod_id,
                "mod_version": rootProject.mod_version,
                "mod_display_name": rootProject.mod_display_name,
                "mod_authors": rootProject.mod_authors,
                "mod_description": rootProject.mod_description,
                "mod_license": rootProject.mod_license,
                "mod_page_url": rootProject.mod_page_url,
                "mod_issues_url": rootProject.mod_issues_url,
                "mod_git_url": rootProject.mod_git_url,
                "mod_discord_url": rootProject.mod_discord_url,
                "neo_version_range": "[${rootProject.neoforge_version},)",
                "minecraft_version_range": "[${rootProject.minecraft_version},)",
                "loader": "neoforge"
        )
    }
}


shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
}

jar {
    archiveClassifier.set("dev")
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = mod_modrinth_id
    versionNumber = mod_version
    versionType = release_channel
    loaders = ["neoforge"]
    file = tasks.named("remapJar").get().archiveFile

    if (changelog_file.exists()) {
        changelog = changelog_file.text
    }

    dependencies {
        required.project 'architectury-api'
        optional.project 'roughly-enough-items'
    }
}